### ISSUE TITLE
Add rando

### ISSUE THREAD

**Issue by witnessmenow** [witnessmenow/Morals-Are-Optional#36]

**Comment by witnessmenow** [comment]
Game logic can now handle rando being added with f483454a3b75eada126808c6461b13bd3b661d81

Just needs a way for the user to add him to the game now, the java code for adding him in is just the following

this.game.players.put("rando", new Rando());

**Comment by nestkimo** [comment]
removed jquery mobile as well as part of this, there is a slight zooming bug which will be fixed with the responsive work.

Also, rando's card is not being displayed to the judge in a random fashion (ironically), this will need to be fixed. Rando will either be first when the game starts or will be put last if a new player joins, from what I've seen so far.

**Comment by witnessmenow** [comment]
Rando is added
